### ISSUE TITLE
Add jibUseCurrentTimestamp as a settingKey to match maven and gradle plugins.

### ISSUE THREAD

**Issue by lerms** [schmitch/sbt-jib#23]
https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#why-is-my-image-created-48-years-ago

Maven and Gradle users have an option. I will open up a PR for this. We can enable this by using jib core, it was exposed via the Jib builder in 0.9.1.

**Comment by lerms** [comment]
Could have write access to this repo to open up a PR? I have it implemented locally for you to have a look.

**Comment by schmitch** [comment]
you can just fork it and make a PR.

**Comment by lerms** [comment]
cool will do.

**Comment by schmitch** [comment]
Closed via #24

**Comment by schmitch** [comment]
Release will be sbt-jib 0.3.0 (takes a while till it's on Maven Central)

**Comment by schmitch** [comment]
actually I will release sbt-jib 0.3.1 since 0.3.0 was compiled with java 11 (which does not on java8)

**Comment by lerms** [comment]
Sounds good, thank you!

**Comment by lerms** [comment]
@schmitch I am having issues with 0.3.1.

```
[error] java.lang.UnsupportedClassVersionError: de/gccc/jib/ZipStripper has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
[error] 	at java.lang.ClassLoader.defineClass1(Native Method)
[error] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
[error] 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[error] 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
[error] 	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
[error] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
[error] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
[error] 	at java.security.AccessController.doPrivileged(Native Method)
[error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error] 	at de.gccc.jib.SbtLayerConfigurations$.reproducibleDependencies(SbtLayerConfigurations.scala:67)
[error] 	at de.gccc.jib.SbtLayerConfigurations$.generate(SbtLayerConfigurations.scala:21)
[error] 	at de.gccc.jib.JibPlugin$.$anonfun$projectSettings$17(JibPlugin.scala:83)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (http-service / sbtLayerConfiguration) java.lang.UnsupportedClassVersionError: de/gccc/jib/ZipStripper has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

I am on Java 8
```
java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)
```

Is this similar to the issue you faced with 0.3.0?

**Comment by schmitch** [comment]
yeah that's the same issue, I'm looking into it

**Comment by lerms** [comment]
Just saw you updated the version, thanks for that! Going to test it out.

**Comment by lerms** [comment]
Works for me, thanks for the update!
